### ISSUE TITLE
Start Contributing

### ISSUE THREAD

**Issue by parth-gr** [moja-global/Google_Summer_of_Code#1]
Hi.
I'm interested in dealing with this issue for GSoC20. Right now I'm reading about Moja - Global

Any advice / suggestions / directions to help me understand this issue clearly?

**Comment by gmajan** [comment]
Hi Parth,
Do you have C++ skills? Then we would be very happy to help you work on the modules or on the core code improvement. 
This is where all the fun is at the moment. :)

**Comment by parth-gr** [comment]
Respected sir, thanks for your reply.

Yes, sir, I am well-versed at C++, from the past 2 years, I am practising competitive programming in C++.

**Comment by gmajan** [comment]
Brilliant.
Can you have a look at the 2 first projects?
If you want to have a real challenge, may I suggest the streamlining of the
core code?

**Comment by parth-gr** [comment]
Sure sir, i will be looking at this project, sir can you please confirm that you're talking about Refactor FLINT Core Code Base.
And can you send some link for the codebase?

**Comment by gmajan** [comment]
Yes I am talking about refactoring the code base.
I have copied Max (Canada) and Mal (Australia) who will be able to provide
you with some details on what we have in mind.
So what sort of C++ competitions have you taken part in?
The code base is in the FLINT repo but you have probably noticed that some
is still in an old repo. We should transfer that code.
Both Max and Mal can give you access to that repo too.
Keep us posted
Guy

**Comment by parth-gr** [comment]
Okay sir,
General Competitions on CodeChef and codeforces, my profile:https://www.codechef.com/users/p4parth,
and I have also dome some of the courses in C++.

Sir, please provide the required link and access to the codebase , so I can learn more about it and can contribute to it asap.
To give access, my Email id is: Partharora1010@gmail.com

**Comment by parth-gr** [comment]
@mfellows and @malfrancis can you please let me know about the codebase and how can I start for the Refactor Flint Code Base.

**Comment by gmajan** [comment]
Hi Parth,
This is just to let you know that Max is based in Victoria, Canada and has
only just gone to bed. I will ask Mal to give you access.
Thx

**Comment by parth-gr** [comment]
okay sir, sir please give asap as by this I can contribute also before the period of sending the proposal.

**Comment by malfrancis** [comment]
Hi Parth,
The repo to get you started would be the FLINT see:
https://github.com/moja-global/FLINT

Cheers 
Mal

**Comment by parth-gr** [comment]
Thanks sir, and sir there is any chat channel to directly communicate and ask doubts.

**Comment by gmajan** [comment]
Hi Parth
I have added you to the Slack channel of moja global.
You can always ask additional questions there.
Let us know how you go.
